
services:
  product-service:
    build: ./product-service
    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"
    restart: always

  inventory-service:
    build: ./inventory-service
    
    volumes:
      - ./data:/app/data
    ports:
      - "8082:8082"
    restart: always

  report-service:
    build: ./report-service
    volumes:
      - ./data:/app/data
    ports:
      - "8083:8083"
    restart: always
