services:
  product-service:
    build: ./product-service
    environment:
      - EXCEL_FILE_PATH=/app/data/products.xlsx
    volumes:
      - ./data:/app/data
    ports:
      - "8081:8081"

  inventory-service:
    build: ./inventory-service
    environment:
      - EXCEL_FILE_PATH=/app/data/products.xlsx
    volumes:
      - ./data:/app/data
    ports:
      - "8082:8082"

  report-service:
    build: ./report-service
    environment:
      - EXCEL_FILE_PATH=/app/data/products.xlsx
    volumes:
      - ./data:/app/data
    ports:
      - "8083:8083"

  purchase-service:
    build: ./purchase-service
    environment:
      - EXCEL_FILE_PATH=/app/data/products.xlsx
    volumes:
      - ./data:/app/data
    ports:
      - "8084:8084"
